version: '0.1'
name: barista-chatbot

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
