name: Barista Chatbot Tests

on:
  push:
    branches:
      - main  # Run the workflow when code is pushed to the main branch
      - dev
  pull_request:
    branches:
      - main  # Run the workflow on pull requests targeting the main branch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 -m pytest

